### ISSUE TITLE
Support variants?

### ISSUE THREAD

**Issue by freitagdavid** [corax89/chip8-test-rom#1]
Would it be possible to have roms for the extended chip8 variants? I'm actually working on an emulator at the moment maybe I could look into what it would take to implement the support myself.

**Comment by corax89** [comment]
I wrote rom for my emulator. My emulator only supports chip-8.

**Comment by freitagdavid** [comment]
Okay, no prob figured it was worth asking.

**Comment by tobiasvl** [comment]
@freitagdavid Let me know if you implement it! I've been considering making something with more coverage myself. If you want to look into it, it's probably easiest to write it in Octo: https://github.com/JohnEarnest/Octo
